services:
  - type: web
    name: async-django-demo
    runtime: python3
    buildCommand: sh build.sh
    startCommand: poetry run python3 manage.py runserver 0.0.0.0:10000
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
