services:
  - type: web
    name: async-django-demo
    runtime: python3
    buildCommand: |
      poetry install
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: poetry run python3 manage.py runserver 0.0.0.0:10000
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: 'False'
